# Generated by Django 4.2.7 on 2024-03-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=150)),
                ('unique_code', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Временный пользователь',
                'db_table': 'TemporaryUser',
            },
        ),
    ]
