# Generated by Django 4.2.7 on 2024-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_temporaryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='unique_code',
            field=models.CharField(),
        ),
    ]
