# Generated by Django 4.2.7 on 2024-03-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_temporaryuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporaryuser',
            options={'verbose_name': 'Временный пользователь'},
        ),
        migrations.AlterModelTable(
            name='temporaryuser',
            table='TemporaryUser',
        ),
    ]
