# Generated by Django 4.2.7 on 2024-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_temporaryuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
