# Generated by Django 4.2.7 on 2024-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_temporaryuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_step_auth',
            field=models.BooleanField(default=False),
        ),
    ]
