# Generated by Django 4.2.7 on 2024-03-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_average_rating_products_count_of_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product_id',
            new_name='product',
        ),
    ]
