# Generated by Django 4.2.7 on 2024-03-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_id',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
